#!/bin/sh
echo 'into'

cyc=$1
namver=$2

mkdir /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch7
cd /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch7
sleep 240

/lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/make_shear ${cyc} ${namver} &
/lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/make_ptnd ${cyc} ${namver} &
/lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/make_parc ${cyc} ${namver} &
/lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/make_lift2 ${cyc} ${namver} &
/lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/make_850_2 ${cyc} ${namver} &
/lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/make_700t2 ${cyc} ${namver} &
/lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/make_thunder2 ${cyc} ${namver}
wait

echo beforestopxvfb7
exit


