#!/bin/sh
echo 'into'

cyc=$1
version=$2

mkdir /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch2/type
cd /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch2/type
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/coltbl.xwp .

year=`cut -c 7-10 /lfs/h1/ops/prod/com/date/t${cyc}z`
month=`cut -c 11-12 /lfs/h1/ops/prod/com/date/t${cyc}z`
date=`cut -c 13-14 /lfs/h1/ops/prod/com/date/t${cyc}z`
yyyymmdd=`cut -c 7-14 /lfs/h1/ops/prod/com/date/t${cyc}z`

date
date > holddate 
echo $holddate
dayoweek=`cut -c 1-3 holddate`
echo $dayoweek

#year=2002
#month=11
#date=10
#yyyymmdd=20021110
#dayoweek=Sun

times="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42"

for fhr in $times; do

fmdl=/lfs/h1/ops/prod/com/nam/${version}/nam.${yyyymmdd}/gempak/nam20_${yyyymmdd}${cyc}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl
 GDATTIM  = f$fhr 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = wxtr 
 CINT     = 0.11;10 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~ GREEN-rain  BLUE-snow  RED-frzrain  PUR-sleet
 DEVICE   = GIF|type${fhr}.gif|700;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/60;-100;30;/1;1;1;0
 GAREA    = 21;-119;53;-60
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0.11;10 
 FLINE    = 0;3
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = wxts
 CLEAR    = n
 FLINE    = 0;26
 r

 GDPFUN   = wxtp
 FLINE    = 0;29
 r

 GDPFUN   = wxtz
 FLINE    = 0;2
 r

ex
EOF

gpend
done

echo paststop
mv *gif ../../launch4/type/.
exit
