#!/bin/sh
echo 'into'

cyc=$1
version=$2
mkdir /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch8/cins
cd /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch8/cins
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/coltbl.xwp .

year=`cut -c 7-10 /lfs/h1/ops/prod/com/date/t${cyc}z`
month=`cut -c 11-12 /lfs/h1/ops/prod/com/date/t${cyc}z`
date=`cut -c 13-14 /lfs/h1/ops/prod/com/date/t${cyc}z`
yyyymmdd=`cut -c 7-14 /lfs/h1/ops/prod/com/date/t${cyc}z`

date
date > holddate 
echo $holddate
dayoweek=`cut -c 1-3 holddate`
echo $dayoweek

#year=2002
#month=11
#date=10
#yyyymmdd=20021110
#dayoweek=Sun

times="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42"
for fhr in $times; do

fmdl=/lfs/h1/ops/prod/com/nam/${version}/nam.${yyyymmdd}/gempak/nam40_${yyyymmdd}${cyc}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl
 GDATTIM  = f$fhr 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = cins 
 CINT     = -400;-350;-300;-250;-200;-150;-100;-50;-25 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~ @  SFC-BASED CONVECTIVE INHIBITION
 DEVICE   = GIF|sfccins${fhr}.gif|700;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/60;-100;30;/1;2;1;1
 GAREA    = 18.;-120.;50.;-58.
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.05;0.92/.8;.02/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -400;-350;-300;-250;-200;-150;-100;-50;-25
 FLINE    = 15;2;17;10;5;23;21;25;28;0
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GLEV     = 180:0
 GVC      = PDLY
 TITLE    = 1/-1/~ @  MOST UNSTABLE CONVECTIVE INHIBITION 
 DEVICE   = GIF|mucins${fhr}.gif|700;900
 CLEAR    = y
r

 GLEV     = 90:0
 TITLE    = 1/-1/~ @  MIXED LAYER CONVECTIVE INHIBITION 
 DEVICE   = GIF|mlcins${fhr}.gif|700;900
r

ex
EOF

gpend
done
echo paststop
mv *gif /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/hold/.
exit
