#!/bin/sh
echo 'into'

cyc=$1
version=$2
mkdir /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch3/24pcp
cd /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch3/24pcp 
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/coltbl.xwp .

year=`cut -c 7-10 /lfs/h1/ops/prod/com/date/t${cyc}z`
month=`cut -c 11-12 /lfs/h1/ops/prod/com/date/t${cyc}z`
date=`cut -c 13-14 /lfs/h1/ops/prod/com/date/t${cyc}z`
yyyymmdd=`cut -c 7-14 /lfs/h1/ops/prod/com/date/t${cyc}z`
gemdate=`cut -c 9-14 /lfs/h1/ops/prod/com/date/t${cyc}z`

date
date > holddate 
echo $holddate
dayoweek=`cut -c 1-3 holddate`
echo $dayoweek

#year=2002
#month=11
#date=10
#yyyymmdd=20021110
#dayoweek=Sun

times="24 36 48 60 72 84" 
for fhr in $times; do

cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/nam218_${yyyymmdd}${cyc} .

    gdplot2 << EOF
 GDFILE   = fmdl
 GDATTIM  = f$fhr 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = p24i 
 CINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;3.5 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~  24-HR TOTAL PRECIP 
 DEVICE   = GIF|24pcp${fhr}.gif|700;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/60;-100;30;/1;2;1;1
 GAREA    = 18;-120;50;-60
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.18;0.93/.7;.02/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;3.5
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = c24i
 CLEAR    = y
 DEVICE   = GIF|24cpcp${fhr}.gif|700;850
 TITLE    = 1/-1/~   24-HR CONVECTIVE PRECIP
r

ex
EOF

done 
gpend

      gdcntr << EOF
 GDFILE   = fmdl
 GDATTIM  = f84
 GLEVEL   = 0
 GVCORD   = none
 GFUN     = add(p48i^${gemdate}/${cyc}f48,p36i)
 CINT     = 0.5 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~  84-HR TOTAL PRECIP
 DEVICE   = GIF|totalpcp.gif|850;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/60;-100;30;/1;2;1;1
 GAREA    = 18;-120;52;-60
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.05;0.96/.8;.02/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;3.5;4;5;6
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;17;10;5
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

 GFUN     = add(c48i^${gemdate}/${cyc}f48,c36i)
 TITLE    = 1/-1/~  84-HR TOTAL CONVECTIVE PRECIP
 DEVICE   = GIF|totalcpcp.gif|850;900
r

ex
EOF
gpend
mv *gif /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/hold/.
exit
