#!/bin/sh
echo 'into'

cyc=$1
version=$2
mkdir /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch5/500
cd /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch5/500
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/coltbl.xwp .

year=`cut -c 7-10 /lfs/h1/ops/prod/com/date/t${cyc}z`
month=`cut -c 11-12 /lfs/h1/ops/prod/com/date/t${cyc}z`
date=`cut -c 13-14 /lfs/h1/ops/prod/com/date/t${cyc}z`
yyyymmdd=`cut -c 7-14 /lfs/h1/ops/prod/com/date/t${cyc}z`

date
date > holddate 
echo $holddate
dayoweek=`cut -c 1-3 holddate`
echo $dayoweek

#year=2002
#month=11
#date=10
#yyyymmdd=20021110
#dayoweek=Sun

times="45 48 51 54 57 60 63 66 69 72 75 78 81 84"
for fhr in $times; do

fmdl=/lfs/h1/ops/prod/com/nam/${version}/nam.${yyyymmdd}/gempak/nam40_${yyyymmdd}${cyc}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl
 GDATTIM  = f$fhr 
 GLEVEL   = 500 
 GVCORD   = pres 
 GDPFUN   = avor(wnd) 
 CINT     = 2/10/46 
 LINE     = 0 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~ 500 MB HGT/VORT
 DEVICE   = GIF|500${fhr}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/60;-100;30;/1;2;1;1
 GAREA    = 14;-126;58;-44
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 5
 LATLON   = 0
 HILO     = 2/x#;/14-46;/5//yes
 HLSYM    = 1//21;//HW
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = 16;20;24;28;32;36
 FLINE    = 0;23;21;5;19;17;16
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = quo(hght,10)
 CINT     = 6
 LINE     = 4/1/4/3
 TITLE    = 0
 CLEAR    = n
 SCALE    = 0
 HILO     = 0
 HLSYM    = 2;2//2/4/SW
 TEXT     = 1.2/11/2
 FINT     = 0
 FLINE    = 0
 TYPE     = c
r

ex
EOF

gpend
done
mv *gif /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/hold/.
exit
