#!/bin/sh
echo 'into'

cyc=$1
version=$2
mkdir /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch1/lift
cd /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch1/lift
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/coltbl.xwp .

year=`cut -c 7-10 /lfs/h1/ops/prod/com/date/t${cyc}z`
month=`cut -c 11-12 /lfs/h1/ops/prod/com/date/t${cyc}z`
date=`cut -c 13-14 /lfs/h1/ops/prod/com/date/t${cyc}z`
da00=`cut -c 7-16 /lfs/h1/ops/prod/com/date/t${cyc}z`
yyyymmdd=`cut -c 7-14 /lfs/h1/ops/prod/com/date/t${cyc}z`

date
date > holddate 
echo $holddate
dayoweek=`cut -c 1-3 holddate`
echo $dayoweek

times="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42"
for fhr in $times; do

fmdl=/lfs/h1/ops/prod/com/nam/${version}/nam.${yyyymmdd}/gempak/nam40_${yyyymmdd}${cyc}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl
 GDATTIM  = f$fhr 
 GLEVEL   = 180:0 
 GVCORD   = pdly 
 GDPFUN   = lft4 
 CINT     = -10;-8;-6;-4;-2;0;16
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~ @  MOST UNSTABLE LIFTED INDEX 
 DEVICE   = GIF|lift${fhr}.gif|700;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/60;-100;30;/1;2;1;1 
 GAREA    = 18.;-120.;50.;-58.
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.05;0.92/.8;.02/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -10;-8;-6;-4;-2;0;16 
 FLINE    = 15;2;30;28;23;21;0;4 
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF

gpend
done

. /u/geoffrey.manikin/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/liftftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/namsvrfcst/images/today
mput *.gif
bye
EOF

ftp -n -v << EOF > /lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/liftftp.out2
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/namsvrfcst/images/${dayoweek}/${cyc}z
mput *gif
bye
EOF

exit
stop
