#!/bin/sh
echo 'into'

cyc=$1
version=$2
mkdir /lfs/h2/emc/stmp/geoffrey.manikin/namsvr
mkdir /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch8
mkdir /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch8/700t
cd /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch8/700t
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/coltbl.xwp .

year=`cut -c 7-10 /lfs/h1/ops/prod/com/date/t${cyc}z`
month=`cut -c 11-12 /lfs/h1/ops/prod/com/date/t${cyc}z`
date=`cut -c 13-14 /lfs/h1/ops/prod/com/date/t${cyc}z`
yyyymmdd=`cut -c 7-14 /lfs/h1/ops/prod/com/date/t${cyc}z`

date
date > holddate 
echo $holddate
dayoweek=`cut -c 1-3 holddate`
echo $dayoweek

#year=2002
#month=11
#date=10
#yyyymmdd=20021110
#dayoweek=Sun

times="45 48 51 54 57 60 63 66 69 72 75 78 81 84"
for fhr in $times; do

fmdl=/lfs/h1/ops/prod/com/nam/${version}/nam.${yyyymmdd}/gempak/nam40_${yyyymmdd}${cyc}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl
 GDATTIM  = f$fhr 
 GLEVEL   = 700 
 GVCORD   = pres 
 GDPFUN   = tmpc
 CINT     = 2 
 LINE     = 0 
 MAP      = 1
 WIND     = BK1/0.7/2/122 
 TITLE    = 1/-1/~ 700 MB TEMP/WINDS (C, knots)
 DEVICE   = GIF|700t${fhr}.gif|800;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/60;-100;30;/1;2;1;1
 GAREA    = 16;-125;56;-51
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.05;0.92/.5;.02/2
 CONTUR   = 0
 SKIP     = /9;9
 FINT     = -10;-8;-6;-4;-2;0;2;4;6;8;10;12;14;16;18  
 FLINE    = 0;30;29;28;27;4;25;23;21;20;5;10;17;11;2;15
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = kntv(wnd)
 TYPE     = b
 TITLE    = 0
 CLRBAR   = 0 
 CLEAR    = n
r

ex
EOF

gpend
done
mv *gif /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/hold/. 
exit
