#!/bin/sh
echo 'into'

cyc=$1
version=$2

Mkdir /lfs/h2/emc/stmp/geoffrey.manikin/namsvr
mkdir /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch2/stm
rm /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch2/stm/*
cd /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch2/stm
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/coltbl.xwp .

year=`cut -c 7-10 /lfs/h1/ops/prod/com/date/t${cyc}z`
month=`cut -c 11-12 /lfs/h1/ops/prod/com/date/t${cyc}z`
date=`cut -c 13-14 /lfs/h1/ops/prod/com/date/t${cyc}z`
yyyymmdd=`cut -c 7-14 /lfs/h1/ops/prod/com/date/t${cyc}z`

date
date > holddate 
echo $holddate
dayoweek=`cut -c 1-3 holddate`
echo $dayoweek

#year=2002
#month=11
#date=10
#yyyymmdd=20021110
#dayoweek=Sun

times="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42"
for fhr in $times; do

fmdl=/lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/nam218_${yyyymmdd}${cyc}

    gdplot2 << EOF

 GDFILE   = $fmdl
 GDATTIM  = f$fhr 
 GLEVEL   = 6000:0 
 GVCORD   = hght 
 GDPFUN   = knts(mag((vecr(ustrm,vstrm)))
 CINT     = 5 
 LINE     = 0 
 MAP      = 1
# WIND     = aK1/0.6/2/122/0.7 
 WIND     = bk1/0.7/2/122
 TITLE    = 1/-1/~ STORM MOTION (knots)
 DEVICE   = GIF|strm${fhr}.gif|800;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/60;-100;30;/1;2;1;1
 GAREA    = 22;-120;48;-60
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.05;0.88/.5;.02/2
 CONTUR   = 0
 SKIP     = /20;20
 FINT     = 5;10;15;20;25;30;35;40;45;50;55;60 
 FLINE    = 0;30;28;27;25;23;21;5;10;17;11;2;15
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = kntv(strm) 
 TYPE     = b
 TITLE    = 0
 CLRBAR   = 0 
 CLEAR    = n
r

ex
EOF

gpend
done
mv *gif /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/hold/.
exit
