#!/bin/sh
echo 'into'

cyc=$1
version=$2
mkdir /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch2/pcp
cd /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch2/pcp
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/coltbl.xwp .

year=`cut -c 7-10 /lfs/h1/ops/prod/com/date/t${cyc}z`
month=`cut -c 11-12 /lfs/h1/ops/prod/com/date/t${cyc}z`
date=`cut -c 13-14 /lfs/h1/ops/prod/com/date/t${cyc}z`
yyyymmdd=`cut -c 7-14 /lfs/h1/ops/prod/com/date/t${cyc}z`

date
date > holddate 
echo $holddate
dayoweek=`cut -c 1-3 holddate`
echo $dayoweek

#year=2002
#month=11
#date=10
#yyyymmdd=20021110
#dayoweek=Sun

times="03 21 57"
for fhr in $times; do

fmdl=/lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/nam218_${yyyymmdd}${cyc}

    gdplot2 << EOF

 GDFILE   = $fmdl
 GDATTIM  = f$fhr 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = p03i 
 CINT     = .01;.1;.2;.3;.4;.5;.75;1.;1.5 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~ @  3-HR TOTAL PRECIP 
 DEVICE   = GIF|3pcp${fhr}.gif|700;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/60;-100;30;/1;2;1;1
 GAREA    = 18;-120;50;-60
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.18;0.93/.6;.02/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.2;.3;.4;.5;.75;1.;1.5;2;2.5 
 FLINE    = 0;21;22;23;4;25;27;28;30;2;15;10;20
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = c03i
 CLEAR    = y
 DEVICE   = GIF|3cpcp${fhr}.gif|700;850
 TITLE    = 1/-1/~ @  3-HR CONVECTIVE PRECIP
r

ex
EOF

gpend
done 

exit
