#!/bin/sh
echo 'into'

cyc=$1
version=$2
mkdir /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch6/pcp
cd /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch6/pcp
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/coltbl.xwp .

year=`cut -c 7-10 /lfs/h1/ops/prod/com/date/t${cyc}z`
month=`cut -c 11-12 /lfs/h1/ops/prod/com/date/t${cyc}z`
date=`cut -c 13-14 /lfs/h1/ops/prod/com/date/t${cyc}z`
yyyymmdd=`cut -c 7-14 /lfs/h1/ops/prod/com/date/t${cyc}z`

date
date > holddate 
echo $holddate
dayoweek=`cut -c 1-3 holddate`
mon=`cut -c 5-7 holddate`
gtime=`cut -c 12-24 holddate`
gdate=`cut -c 1-10 holddate`
gcent=`cut -c 25-28 holddate`
echo $dayoweek

#year=2002
#month=11
#date=10
#yyyymmdd=20021110
#dayoweek=Sun

times="57 60 63 66 69 72 75 78 81 84"
for fhr in $times; do

fmdl=/lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/nam218_${yyyymmdd}${cyc}

    gdplot2 << EOF
 GDFILE   = $fmdl
 GDATTIM  = f$fhr 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = p03i 
 CINT     = .01;.1;.2;.3;.4;.5;.75;1.;1.5 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~ @  3-HR TOTAL PRECIP 
 DEVICE   = GIF|3pcp${fhr}.gif|700;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/60;-100;30;/1;2;1;1
 GAREA    = 18;-120;50;-60
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.18;0.93/.6;.02/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.2;.3;.4;.5;.75;1.;1.5;2;2.5 
 FLINE    = 0;21;22;23;4;25;27;28;30;2;15;10;20
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = c03i
 CLEAR    = y
 DEVICE   = GIF|3cpcp${fhr}.gif|700;850
 TITLE    = 1/-1/~ @  3-HR CONVECTIVE PRECIP
r

ex
EOF

gpend
done 

cat > info.html <<EOFmet
<HTML>
<BODY bgcolor="FFCC99">
<CENTER><H2><b><u>NCEP NAM CONVECTIVE FORECASTING PAGE</H2></CENTER></u></b>
<p>
<CENTER>
The current forecast cycle is <b><font face="Times New Roman,Times"><font size=+1><font color="#CC0000">${cyc}Z ${date} ${mon} </font><font color="#FF6600"></font></font></font></b> with graphics finished at $gtime $gdate $gcent
</CENTER>
<p>
This page displays 00/12Z NAM model forecasts of convective parameters from the operational 12-km NAM model  Some of the newer fields such as 0-1km storm-relative helicity and 
<a href="http://www.emc.ncep.noaa.gov/mmb/tips/tip.jul02.html">mixed-layer CAPE</a> are not widely available to the field, so this site offers a chance to examine more model output.   Check out a complete documentation of the output from the <a href="http://www.emc.ncep.noaa.gov/mmb/papers/chuang/1/OF438.html">Eta Post Processor</a>.

<H4>NOTE: All displayed winds are in knots.  Precipitation values are in inches.</H4>
<p>
GRIB files from the operational NAM-12 forecast can be found <a href='ftp://ftpprd.ncep.noaa.gov/pub/data/nccf/com/nam/${version}/nam.${yyyymmdd}/'> on the NCEP ftp server</a> or at the <a href='ftp://tgftp.nws.noaa.gov/SL.us008001/ST.opnl/MT.nam_CY.${CYC}/RD.${yyyymmdd}/PT.grid_DF.gr1/' > NWS Gateway server</a>. Descriptions of some of these output files can be found at the <a href='http://www.emc.ncep.noaa.gov/mmb/etagrids/' >EMC NAM Grid Domains</a> page.
<p>
<img src ="../www_images/graysquare_line.gif"> </a>
<p>
<b><font face="Times New Roman,Times"><font size=+1><font color="#993399">CHECK OUT THESE OTHER EMC WEB PAGES WITH CONVECTIVE FORECASTING INFO </font>
<p>
<H4><img src ="../www_images/eye_dot.gif"></a><TH><a href="http://www.emc.ncep.noaa.gov/mmb/nammeteograms"TARGET=_blank> NAM Meteograms</a></H4></TH>
<H4><img src ="../www_images/eye_dot.gif"></a><TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/rucmeteograms"TARGET=_blank> RUC Meteograms</A></H4></TH>
<H4><img src ="../www_images/eye_dot.gif"></a><TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/soundings.nam/snding.html"TARGET=_blank> NAM Forecast Soundings</A></H4></TH>
<img src ="../www_images/graysquare_line.gif">
<p>
<H2> Get the forecasts for the previous 7 days here (link opens a new window):</H2><p>
<TABLE BORDER>
<THEAD>
<TR>
<TH>SUNDAY</TH>
<TH>MONDAY</TH>
<TH>TUESDAY</TH>
<TH>WEDNESDAY</TH>
<TH>THURSDAY</TH>
<TH>FRIDAY</TH>
<TH>SATURDAY</TH>
</TR>

<TBODY>
<TR>
<TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/namsvrfcst/images/Sun/12z/"TARGET=_blank>12z</A></TH>
<TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/namsvrfcst/images/Mon/12z/"TARGET=_blank>12z</A></TH>
<TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/namsvrfcst/images/Tue/12z/"TARGET=_blank>12z</A></TH>
<TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/namsvrfcst/images/Wed/12z/"TARGET=_blank>12z</A></TH>
<TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/namsvrfcst/images/Thu/12z/"TARGET=_blank>12z</A></TH>
<TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/namsvrfcst/images/Fri/12z/"TARGET=_blank>12z</A></TH>
<TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/namsvrfcst/images/Sat/12z/"TARGET=_blank>12z</A></TH>
</TR>
<TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/namsvrfcst/images/Sun/00z/"TARGET=_blank>00z</A></TH>
<TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/namsvrfcst/images/Mon/00z/"TARGET=_blank>00z</A></TH>
<TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/namsvrfcst/images/Tue/00z/"TARGET=_blank>00z</A></TH>
<TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/namsvrfcst/images/Wed/00z/"TARGET=_blank>00z</A></TH>
<TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/namsvrfcst/images/Thu/00z/"TARGET=_blank>00z</A></TH>
<TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/namsvrfcst/images/Fri/00z/"TARGET=_blank>00z</A></TH>
<TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/namsvrfcst/images/Sat/00z/"TARGET=_blank>00z</A></TH>
</TR>
</TABLE>
<p>
<img src ="../www_images/graysquare_line.gif">
<p>
<H4><i>EMC DISCLAIMER : This web page is not "operational" and therefore
not subject to 24-h monitoring by NCEP's Central Operations staff.</i></H4>
<p>
<center> <a href='http://www.nws.noaa.gov/disclaimer1.html'>NWS Disclaimer</a> </c
enter>
<img src ="../www_images/graysquare_line.gif"> </a>
</BODY>
</HTML>
EOFmet

cat > info2.html <<EOFmet
<HTML>
<BODY bgcolor="FFCC99">
<CENTER><H2><b><u>NCEP nam CONVECTIVE FORECASTING PAGE</H2></CENTER></u></b>
<p>
<CENTER>
The current forecast cycle is <b><font face="Times New Roman,Times"><font size=+1><font color="#CC0000">${cyc}Z ${date} ${mon} </font><font color="#FF6600"></font></font></font></b> with graphics finished at $gtime $gdate $gcent
</CENTER>
<p>
This page displays 00/12Z nam model forecasts of convective parameters from the operational 12-km NAM model  Some of the newer fields such as 0-1km storm-relative helicity and<a href="http://www.emc.ncep.noaa.gov/mmb/tips/tip.jul02.html">mixed-layer CAPE</a> are not widely available to the field, so this site offers a chance to examine more model output.   Check out a complete documentation of the output from the <a href="http://www.emc.ncep.noaa.gov/mmb/papers/chuang/1/OF438.html">Eta Post Processor</a>.

<H4>NOTE: All displayed winds are in knots.  Precipitation values are in inches.</H4>
<p>
<img src ="../../../../www_images/graysquare_line.gif"> </a>
<p>
<b><font face="Times New Roman,Times"><font size=+1><font color="#993399">CHECK OUT THESE OTHER EMC WEB PAGES WITH CONVECTIVE FORECASTING INFO </font>
<p>
<H4><img src ="../../../../www_images/eye_dot.gif"></a><TH><a href="http://www.emc.ncep.noaa.gov/mmb/nammeteograms"TARGET=_blank> NAM Meteograms</a></H4></TH>
<H4><img src ="../../../../www_images/eye_dot.gif"></a><TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/rucmeteograms"TARGET=_blank> RUC Meteograms</A></H4></TH>
<H4><img src ="../../../../www_images/eye_dot.gif"></a><TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/namsoundings/snding.html"TARGET=_blank> NAM Forecast Soundings</A></H4></TH>
<img src ="../../../../www_images/graysquare_line.gif">
<p>
<p>
<img src ="../../../../www_images/graysquare_line.gif">
<p>
<H4><i>EMC DISCLAIMER : This web page is not "operational" and therefore
not subject to 24-h monitoring by NCEP's Central Operations staff.</i></H4>
<p>
<center> <a href='http://www.nws.noaa.gov/disclaimer1.html'>NWS Disclaimer</a> </center>
<img src ="../../../../www_images/graysquare_line.gif"> </a>
</BODY>
</HTML>
EOFmet

mv *gif /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/hold/.
mv *html /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/hold/.
exit
