#!/bin/sh
echo 'into'

cyc=$1
version=$2
mkdir /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch6/cape
cd /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch6/cape
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/coltbl.xwp .

year=`cut -c 7-10 /lfs/h1/ops/prod/com/date/t${cyc}z`
month=`cut -c 11-12 /lfs/h1/ops/prod/com/date/t${cyc}z`
date=`cut -c 13-14 /lfs/h1/ops/prod/com/date/t${cyc}z`
da00=`cut -c 7-16 /lfs/h1/ops/prod/com/date/t${cyc}z`
yyyymmdd=`cut -c 7-14 /lfs/h1/ops/prod/com/date/t${cyc}z`

date
date > holddate 
echo $holddate
dayoweek=`cut -c 1-3 holddate`
echo $dayoweek

#year=2002
#month=11
#date=10
#yyyymmdd=20021110
#dayoweek=Sun

times="45 48 51 54 57 60 63 66 69 72 75 78 81 84"
for fhr in $times; do

fmdl=/lfs/h1/ops/prod/com/nam/${version}/nam.${yyyymmdd}/gempak/nam40_${yyyymmdd}${cyc}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl
 GDATTIM  = f$fhr 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = cape 
 CINT     = 50;500;1000;1500;2000;2500;3000;3500;4000;4500;5000
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~ @  SFC-BASED CAPE 
 DEVICE   = GIF|sfccape${fhr}.gif|700;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/60;-100;30;/1;2;1;1 
 GAREA    = 18.;-120.;50.;-58. 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.05;0.92/.8;.02/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = 50;500;1000;1500;2000;2500;3000;3500;4000;4500;5000
 FLINE    = 0;25;21;22;23;5;10;17;16;2;15;32 
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GLEV     = 180:0
 GVC      = PDLY
 TITLE    = 1/-1/~ @  MOST UNSTABLE CAPE
 DEVICE   = GIF|mucape${fhr}.gif|700;900
 CINT     = 50;500;1000;1500;2000;2500;3000;3500;4000;4500;5000
 CLEAR    = y
r

 GLEV     = 90:0
 TITLE    = 1/-1/~ @  MIXED LAYER CAPE
 DEVICE   = GIF|mlcape${fhr}.gif|700;900
 CINT     = 50;500;1000;1500;2000;2500;3000;3500;4000;4500;5000
r

 GLEV     = 255:0
 TITLE    = 1/-1/~   300 MB MOST UNSTABLE CAPE
 DEVICE   = GIF|300cape${fhr}.gif|700;900
r

ex
EOF

gpend
done
mv *gif /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/hold/.
exit
