#!/bin/sh
echo 'into'

cyc=$1
version=$2
mkdir /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch7/shear
rm /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch7/shear/*
cd /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch7/shear
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/coltbl.xwp .

year=`cut -c 7-10 /lfs/h1/ops/prod/com/date/t${cyc}z`
month=`cut -c 11-12 /lfs/h1/ops/prod/com/date/t${cyc}z`
date=`cut -c 13-14 /lfs/h1/ops/prod/com/date/t${cyc}z`
yyyymmdd=`cut -c 7-14 /lfs/h1/ops/prod/com/date/t${cyc}z`

date
date > holddate 
echo $holddate
dayoweek=`cut -c 1-3 holddate`
echo $dayoweek

#year=2002
#month=11
#date=10
#yyyymmdd=20021110
#dayoweek=Sun

times="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42"
for fhr in $times; do

fmdl=/lfs/h1/ops/prod/com/nam/${version}/nam.${yyyymmdd}/gempak/nam40_${yyyymmdd}${cyc}f0${fhr}

   gdplot2 << EOF
 GDATTIM  = f${fhr} 
 GLEVEL   = 6000 
 GVCORD   = ZAGL 
 GDPFUN   = mag(kntv(vsub(wnd@6000,wnd@10%hght)))
 GDFILE   = $fmdl 
 DEVICE   = GIF|shear${fhr}.gif|750;900
 SKIP     = 2;2 
 SATFIL   =
 RADFIL   =
 IMCBAR   =
 SKIP     = 0
 CINT     = 10
 TYPE     = f
 FLINE    = 0;28;26;23;21;5;10;2
 FINT     = 30;40;50;60;70;80;90
 WIND     = bk1/0.5/0.3
 REFVEC   =
 MAP      = 1
 MSCALE   =
 LATLON   = 0
 PROJ     = lcc/60;-100;30;/1;2;1;1
 GAREA    = 24.;-119.;50.;-63.
 PANEL    = 0
 TITLE    = 1/-1/~  0-6 KM SHEAR VECTORS 
 CLRBAR   = 1/H/UL/.05;0.95/.6;.02/1
 CLEAR    = YES
 SCALE    = 0
 TEXT     = 1.1/11/2/SW 
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 GDPFUN   = kntv(vsub(wnd@6000,wnd@10%hght))
 TYPE     = b 
r

ex
EOF

gpend
done
mv *gif /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/hold/.
exit
