#!/bin/sh
echo 'into'

cyc=$1
version=$2

mkdir /lfs/h2/emc/stmp/geoffrey.manikin/etasvr/launch3/zpbl
cd /lfs/h2/emc/stmp/geoffrey.manikin/etasvr/launch3/zpbl
rm /lfs/h2/emc/stmp/geoffrey.manikin/etasvr/launch3/zpbl/*
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/coltbl.xwp .

year=`cut -c 7-10 /lfs/h1/ops/prod/com/date/t${cyc}z`
month=`cut -c 11-12 /lfs/h1/ops/prod/com/date/t${cyc}z`
date=`cut -c 13-14 /lfs/h1/ops/prod/com/date/t${cyc}z`
da00=`cut -c 7-16 /lfs/h1/ops/prod/com/date/t${cyc}z`
yyyymmdd=`cut -c 7-14 /lfs/h1/ops/prod/com/date/t${cyc}z`

date
date > holddate 
echo $holddate
dayoweek=`cut -c 1-3 holddate`
echo $dayoweek

#year=2002
#month=11
#date=10
#yyyymmdd=20021110
#dayoweek=Sun

#times="00 03 06 09 12 15 18 21 24 27 30 33"
times="12 24"
for fhr in $times; do

fmdl=/lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/nam215_${yyyymmdd}${cyc}

    gdplot2 << EOF

 GDFILE   = $fmdl
 GDATTIM  = f$fhr 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = sub(zpbl,hght) 
 CINT     = 100;200;300;400;500;750;1000;1250;1500;2000;2500 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~    PBL HEIGHT
 DEVICE   = GIF|zpbl${fhr}.gif|700;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/60;-100;30;/1;2;1;1 
 GAREA    = 18.;-120.;50.;-58.
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.05;0.92/.8;.02/1
 CONTUR   = 0
 SKIP     = 0
 FLINE    = 0;30;28;25;4;23;21;20;17;2;15
 FINT     = 100;200;300;400;500;750;1000;1250;1500;2000;2500 
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF

gpend
done

. /u/geoffrey.manikin/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/zpblftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/namsvrfcst/images/today
mput *.gif
bye
EOF

ftp -n -v << EOF > /lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/zpblftp.out2
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/namsvrfcst/images/${dayoweek}/${cyc}z
mput *gif
bye
EOF

mv *gif /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/hold/.
exit
