#!/bin/sh
echo 'into'

cyc=$1
version=$2
mkdir /lfs/h2/emc/stmp/geoffrey.manikin/namsvr
mkdir /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch7/ptnd
rm /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch7/ptnd/*
cd /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch7/ptnd
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/coltbl.xwp .

year=`cut -c 7-10 /lfs/h1/ops/prod/com/date/t${cyc}z`
month=`cut -c 11-12 /lfs/h1/ops/prod/com/date/t${cyc}z`
date=`cut -c 13-14 /lfs/h1/ops/prod/com/date/t${cyc}z`
yyyymmdd=`cut -c 7-14 /lfs/h1/ops/prod/com/date/t${cyc}z`
gemdate=`cut -c 9-14 /lfs/h1/ops/prod/com/date/t${cyc}z`

date
date > holddate 
echo $holddate
dayoweek=`cut -c 1-3 holddate`
echo $dayoweek

#year=2002
#month=11
#date=10
#yyyymmdd=20021110
#dayoweek=Sun

times="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42"
for fhr in $times; do

fhr2=`expr $fhr - 3`
fmdl=/lfs/h1/ops/prod/com/nam/${version}/nam.${yyyymmdd}/gempak/nam40_${yyyymmdd}${cyc}f0${fhr}
fmdl2=/lfs/h1/ops/prod/com/nam/${version}/nam.${yyyymmdd}/gempak/nam40_${yyyymmdd}${cyc}f0${fhr2}

if test $fhr2 -lt '10'
then
 fmdl2=/lfs/h1/ops/prod/com/nam/${version}/nam.${yyyymmdd}/gempak/nam40_${yyyymmdd}${cyc}f00${fhr2}
fi
echo $fmdl2

    gdcntr << EOF
 GDFILE   = $fmdl2 + $fmdl
 GDATTIM  = f$fhr2 
 GLEVEL   = 0 
 GVCORD   = none 
 GFUNC    = sub(pmsl^${gemdate}/${cyc}f$fhr+2,pmsl)
 CINT     = 1/-10/-2
 LINE     = 0 
 MAP      = 1
 WIND     = 0 
 TITLE    = 1/-1/~  3-HR SLP TENDENCY 
 DEVICE   = GIF|ptnd${fhr}.gif|800;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/60;-100;30;/1;2;1;1
 GAREA    = 18.;-120.;50.;-58. 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.05;0.89/.4;.02/1
 CONTUR   = 0
 SKIP     = /2;2
 FINT     = -5;-4;-3;-2
 FLINE    = 15;2;17;10;0 
 CTYPE    = f 
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 CINT     = 1/3/10
 LINE     = 0
 FINT     = 2;3;4;5
 FLINE    = 0;27;25;4;24
 CLRBAR   = 1/H/UL/.55;0.89/.4;.02/1
  
r

ex
EOF

gpend
done
mv *gif /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/hold/.
exit
