#!/bin/sh
echo 'into'

cyc=$1
version=$2

mkdir /lfs/h2/emc/stmp/geoffrey.manikin/namsvr
mkdir /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/swem
rm /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/swem/*
cd /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/swem
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/coltbl.xwp .

ymdh=`cut -c 7-16 /lfs/h1/ops/prod/com/date/t${cyc}z`
ymd=`cut -c 7-14 /lfs/h1/ops/prod/com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

times="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42"
for fhr in $times; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam12_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = quo(mul(sndm,100),2.54) 
 CINT     = 2 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~  SNOW DEPTH 
 DEVICE   = GIF|sndm${fhr}.gif|700;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/60;-100;30;/1;2;1;1
 GAREA    = 18;-120;50;-60
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.2/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.02;0.92/.95;.03/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0.1;1;3;5;7.5;10;15;20;25;50;75;100;125
 FLINE    = 0;28;26;4;21;23;20;5;10;17;2;15;9;32
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

ex
EOF
gpend
done
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/namsvrfcst/images/today
mv *gif /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/hold/.
exit
