#!/bin/sh
echo 'into'

cyc=$1
version=$2
mkdir /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch3/hlcy
cd /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch3/hlcy
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/coltbl.xwp .

cyc=`cut -c 15-16 /lfs/h1/ops/prod/com/date/t${cyc}z`
year=`cut -c 7-10 /lfs/h1/ops/prod/com/date/t${cyc}z`
month=`cut -c 11-12 /lfs/h1/ops/prod/com/date/t${cyc}z`
date=`cut -c 13-14 /lfs/h1/ops/prod/com/date/t${cyc}z`
da00=`cut -c 7-16 /lfs/h1/ops/prod/com/date/t${cyc}z`
yyyymmdd=`cut -c 7-14 /lfs/h1/ops/prod/com/date/t${cyc}z`

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
echo $dayoweek

#cyc=00
#year=2002
#month=11
#date=10
#yyyymmdd=20021110
#dayoweek=Sun

times="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42"
for fhr in $times; do

fmdl=/lfs/h1/ops/prod/com/nam/${version}/nam.${yyyymmdd}/gempak/nam40_${yyyymmdd}${cyc}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl
 GDATTIM  = f$fhr 
 GLEVEL   = 3000:0 
 GVCORD   = hght 
 GDPFUN   = hlcy 
 CINT     = 50;100;150;200;250;300;400;500;600;700
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~ @  STORM-RELATIVE HELICITY 
 DEVICE   = GIF|3000hlcy${fhr}.gif|700;800
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/60;-100;30;/1;2;1;1 
 GAREA    = 18.;-119.;50.;-59.
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.05;0.92/.75;.02/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = 50;100;150;200;250;300;400;500;600;700 
 FLINE    = 0;24;25;21;22;23;5;10;17;16;2;15 
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GLEV     = 1000:0
 DEVICE   = GIF|1000hlcy${fhr}.gif|700;800
 CLEAR    = y
r

ex
EOF

gpend
done
mv *gif /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/hold/.
exit
