#!/bin/sh
echo 'into'

cyc=$1
version=$2

mkdir /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch7/trw
cd /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch7/trw
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/coltbl.xwp .
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/gempak/nagrib/ncepgrib2.tbl .

year=`cut -c 7-10 /lfs/h1/ops/prod/com/date/t${cyc}z`
month=`cut -c 11-12 /lfs/h1/ops/prod/com/date/t${cyc}z`
date=`cut -c 13-14 /lfs/h1/ops/prod/com/date/t${cyc}z`
ymd=`cut -c 7-14 /lfs/h1/ops/prod/com/date/t${cyc}z`
ymdh=`cut -c 7-16 /lfs/h1/ops/prod/com/date/t${cyc}z`
DAPATH=/lfs/h1/ops/prod/com/nam/${version}/nam.${ymd}

date
date > holddate 
echo $holddate
dayoweek=`cut -c 1-3 holddate`
echo $dayoweek

#year=2002
#month=11
#date=10
#yyyymmdd=20021110
#dayoweek=Sun

times="45 48 51 54 57 60 63 66 69 72 75 78 81 84"
for fhr in $times; do

WGRIB=/lfs/h1/ops/prod/nwprod/grib_util.v1.0.6/exec/wgrib
$WGRIB ${DAPATH}/nam.t${cyc}z.awip12${fhr}.tm00 | grep kpds5=187 | $WGRIB ${DAPATH}/nam.t${cyc}z.awip12${fhr}.tm00 -i -grib -o new.grd

  nagrib << EOF
GBFILE  = new.grd
INDXFL  =
GDOUTF  = namthunderf${fhr}.grd
PROJ    =
GRDAREA =
KXKY    =
GAREA   = grid
MAXGRD  = 5000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

ex
EOF

fmdl=namthunderf${fhr}.grd

    gdplot2 << EOF
 GDFILE   = $fmdl
 GDATTIM  = f$fhr 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = ltng 
 CINT     = 1 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~  NAM THUNDER 
 DEVICE   = GIF|trw${fhr}.gif|700;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/60;-100;30;/1;2;1;1 
 GAREA    = 20.;-120.;48.;-58.
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0.9;10 
 FLINE    = 0;2
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF

gpend
done
mv *gif /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/hold/.
exit
stop
