#!/bin/sh
echo 'into'

cyc=$1
version=$2
mkdir /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch6/cloud
rm /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch6/cloud/*
cd /lfs/h2/emc/stmp/geoffrey.manikin/namsvr/launch6/cloud
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/coltbl.xwp .

year=`cut -c 7-10 /lfs/h1/ops/prod/com/date/t${cyc}z`
month=`cut -c 11-12 /lfs/h1/ops/prod/com/date/t${cyc}z`
date=`cut -c 13-14 /lfs/h1/ops/prod/com/date/t${cyc}z`
da00=`cut -c 7-16 /lfs/h1/ops/prod/com/date/t${cyc}z`
yyyymmdd=`cut -c 7-14 /lfs/h1/ops/prod/com/date/t${cyc}z`

date
date > holddate 
echo $holddate
dayoweek=`cut -c 1-3 holddate`
echo $dayoweek

times="57 60 63 66 69 72 75 78 81 84"
for fhr in $times; do

fmdl=/com/nawips/prod/nam.${yyyymmdd}/nam40_${yyyymmdd}${cyc}f0${fhr}

    gdplot2 << EOF

 GDFILE   = $fmdl
 GDATTIM  = f$fhr 
 GLEVEL   = 0
 GVCORD   = hcly 
 GDPFUN   = cldh
 CINT     = 10
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~ CLOUD COVERAGE  RED-low  GREEN-mid  BLUE-high (darker=higher %)
 DEVICE   = GIF|cloud${fhr}.gif|800;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/60;-100;30;/1;2;1;1
 GAREA    = 18.;-120.;50.;-58.
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = 10;50;90
 FLINE    = 0;26;25;4
 TYPE     = f
r

 GVCORD   = mcly
 GDPFUN   = cldm
 TITLE    = 0
 FLINE    = 0;21;22;23
 CLEAR    = n
r

 GVCORD   = lcly
 GDPFUN   = cldl
 FLINE    = 0;11;12;2
 CLEAR    = n
 TITLE    = 1/1/  LOWEST CLOUD PLOTTED WHEN MORE THAN ONE LEVEL IS PRESENT
r

ex
EOF

gpend
done

. /u/geoffrey.manikin/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/cloudftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/namsvrfcst/images/today
mput *.gif
bye
EOF

ftp -n -v << EOF > /lfs/h2/emc/vpppg/save/geoffrey.manikin/namsvrfcst/cloudftp.out2
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/namsvrfcst/images/${dayoweek}/${cyc}z
mput *gif
bye
EOF

exit
stop
